### Site Settings ###
title               : Benjamin Bisping
description         : "Research in Semantics and Security of Distributed Systems"
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url                 : "https://bbisping.de"
remote_theme        : YoussefRaafatNasry/portfolYOU

### Plugins ###
plugins:
  - jekyll-remote-theme

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html

### Author Info ###
author:
  name              : Benjamin Bisping
  image             : "assets/img/bb-defense.jpg"
  email             : benjamin.bisping@telecom-sudparis.eu
  orcid             : 0000-0002-0637-0171
  googlescholar     : citations?user=D1Pt_VsAAAAJ
  linkedin          : bbisping
  mastodon          : bisping
  github            : benkeks
  bluesky           : benkeks.bsky.social
  homepage          : https://bbisping.de
  office            : Room 4A251 @ Télécom SudParis, Institut Polytechnique de Paris (19 place Marguerite Perey, 91120 Palaiseau, France)

### Posts ###
permalink: /blog/:title

### Collections ###
# collections:
#   projects:
#     output: true
#     permalink: /:name

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - docs
